### ISSUE TITLE
Clean up function declarations

### ISSUE THREAD

**Issue by kochis** [bonobos/styleguide#5]
* Change any `export function` to use `arrow` syntax
```js
// from
export function myFunction() { ... }

// to
export const myFunction = () => { ... }
```

* If there's any local function (not exported) using `const fn = () => { }`, those can be updated to `function` definitions. 

* Check if this can be enforced via ESLint

**Comment by kochis** [comment]
I'm gonna take this one

**Comment by scottcrawford03** [comment]
take it!
